spring:
  cache:
    type:
      redis
  config:
    activate:
      on-profile: prod

  # Kafka 설정
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS} # Kafka 접속 정보 지정
    producer:
      #직렬화
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    topic:
      topics:
        reservation-event: reservation-event-topic


  # DB 설정: Spring 표준 키 사용 (Doppler에 있는 키와 매칭)
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  # Flyway 완전 비활성화
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: "0"
    locations:
      - classpath:db/migration/mariadb

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION}
  refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}

logging:
  level:
    root: WARN
    com.beyond.qiin: INFO

gemini:
  base-url: https://generativelanguage.googleapis.com/v1beta
  api-key: ${GEMINI_API_KEY}

  #답변 모델
  model: ${GEMINI_MODEL:gemini-3.1-flash-lite}

  #embedding 모델
  embedding-model: ${GEMINI_EMBEDDING_MODEL:gemini-embedding-2}
  temperature: 0.2

#document chunk에 대한 embedding 용
rag:
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: "0"
    locations: classpath:db/migration/postgresql
  datasource:
    url: ${RAG_POSTGRES_DATASOURCE_URL}
    username: ${RAG_POSTGRES_DATASOURCE_USERNAME}
    password: ${RAG_POSTGRES_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
