#전역 설정
global:
  scrape_interval: 5s # 5초마다 데이터 수집(부하테스트용)

#감시할 대상에 대한 정의
scrape_configs:
  # spring boot application
  - job_name: 'spring-app'
    metrics_path: '/actuator/prometheus' #앱 안으로 접근해야하는 경로
    static_configs:
      - targets: ['qiin-app:8080'] #데이터를 가져올 목적지 (컨테이너 이름)

  # maria db
  - job_name: 'mariadb'
    static_configs: #maria db 는 직접 프로메테우스를 이해하지 못하기 때문에 중간에 mariadb-exporter을 둬야함
      - targets: ['mariadb-exporter:9104']
