ALTER TABLE `role_permission`
    ADD PRIMARY KEY (`role_permission_id`);

ALTER TABLE `user` MODIFY `user_id` BIGINT(20) NOT NULL AUTO_INCREMENT;
ALTER TABLE `user_rev` MODIFY `user_rev_id` BIGINT(20) NOT NULL AUTO_INCREMENT;
ALTER TABLE `user_role` MODIFY `user_role_id` BIGINT(20) NOT NULL AUTO_INCREMENT;
ALTER TABLE `user_history` MODIFY `user_history_id` BIGINT(20) NOT NULL AUTO_INCREMENT;
ALTER TABLE `permission` MODIFY `permission_id` BIGINT(20) NOT NULL AUTO_INCREMENT;
ALTER TABLE `department` MODIFY `dpt_id` BIGINT(20) NOT NULL AUTO_INCREMENT;
ALTER TABLE `role` MODIFY `role_id` BIGINT(20) NOT NULL AUTO_INCREMENT;
ALTER TABLE `role_permission` MODIFY `role_permission_id` BIGINT(20) NOT NULL AUTO_INCREMENT;
ALTER TABLE `asset` MODIFY `asset_id` BIGINT(20) NOT NULL AUTO_INCREMENT;
ALTER TABLE `asset_history` MODIFY `asset_history_id` BIGINT(20) NOT NULL AUTO_INCREMENT;
ALTER TABLE `category` MODIFY `category_id` BIGINT(20) NOT NULL AUTO_INCREMENT;
ALTER TABLE `reservation` MODIFY `reservation_id` BIGINT(20) NOT NULL AUTO_INCREMENT;
ALTER TABLE `settlement` MODIFY `settlement_id` BIGINT(20) NOT NULL AUTO_INCREMENT;
ALTER TABLE `notification` MODIFY `event_outbox_id` BIGINT(20) NOT NULL AUTO_INCREMENT;
ALTER TABLE `usage_history` MODIFY `usage_history_id` BIGINT(20) NOT NULL AUTO_INCREMENT;
