CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE rag_document
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY,
    title             VARCHAR(255) NOT NULL,
    source_url        VARCHAR(1000) NOT NULL,
    chunking_strategy VARCHAR(30) NOT NULL,
    created_by        BIGINT NOT NULL,
    created_at        TIMESTAMP(6) NOT NULL,
    updated_by        BIGINT NOT NULL,
    updated_at        TIMESTAMP(6) NOT NULL,
    deleted_by        BIGINT NULL,
    deleted_at        TIMESTAMP(6) NULL,
    PRIMARY KEY (id)
);

CREATE TABLE document_chunk
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    document_id BIGINT NOT NULL,
    chunk_index INT NOT NULL,
    source_key  VARCHAR(100) NOT NULL,
    content     TEXT NOT NULL,
    embedding   vector(1536) NOT NULL,
    created_by  BIGINT NOT NULL,
    created_at  TIMESTAMP(6) NOT NULL,
    updated_by  BIGINT NOT NULL,
    updated_at  TIMESTAMP(6) NOT NULL,
    deleted_by  BIGINT NULL,
    deleted_at  TIMESTAMP(6) NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_document_chunk_document
        FOREIGN KEY (document_id)
        REFERENCES rag_document (id)
);
