server:
  port: ${SERVER_PORT:8080} # 환경 변수가 없으면 기본값 8080 사용

spring:
  profiles:
    default: ${SPRING_PROFILES_ACTIVE:dev}
  application:
    name: qiin-app

  mvc:
    async:
      request-timeout: 3600000 #1h(sse 연결 시간)

  # JPA 공통 설정
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

  datasource:
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      connection-timeout: 30000


  # ----------------------------------------
  # AWS SES SMTP (이메일 발송) 설정 추가
  # ----------------------------------------
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# ----------------------------------------
# 발신자 정보 설정 (MailService에서 사용) 추가
# ----------------------------------------
mail:
  from: ${MAIL_FROM}

login:
  url: ${LOGIN_URL}

# JWT 설정
jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION}
  refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}

management:
  endpoints: #http 로 정보 외부로 노출
    web:
      exposure: #/actuator/prometheus, /actuator/health, /actuator/info의 경로
        include: prometheus, health, info #프로메테우스가 읽어갈 수 있는 형식의 데이터, 서버의 상태(up, down), 애플리케이션 정보
  endpoint:
    prometheus:
      enabled: true #프로메테우스용 데이터 수집 활성화
    health:
      show-details: always # 헬스체크 상세 정보 포함해서 제공
  metrics: #성능 데이터에 대한 이름표
    tags:
      application: ${spring.application.name}

logging:
  level:
    org.springframework: INFO
    com.domino.smerp: INFO
